// Constants used to make sure two actions does not have the same name.
export const TEST_ACTION = "TEST_ACTION";
export const SET_RELATION = "SET_RELATION";

export const SET_ACTIVE_WINDOW = 'SET_ACTIVE_WINDOW';
export const OUTPUT_NEXT_PAGE = "NEXT_PAGE";
export const OUTPUT_PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const RESET_PAGE_NUMBER = "RESET_PAGE_NUMBER";
export const SET_OUTPUT_TEXT = "SET_OUTPUT_TEXT";
export const SET_GREMLIN_QUERY_DISPLAY_TEXT = "SET_GREMLIN_QUERY_DISPLAY_TEXT"
export const SET_AUTOCOMPLETE_OPTIONS = "SET_AUTOCOMPLETE_OPTIONS"
export const AUTOCOMPLETE_SET_DEBUG = "AUTOCOMPLETE_SET_DEBUG"
export const SET_INITIAL_SEARCH_PARAMETER = "SET_INITIAL_SEARCH_PARAMETER";
export const RESET_CURRENT_GREMLIN_QUERY = "RESET_CURRENT_GREMLIN_QUERY"
export const APPEND_TO_CURRENT_GREMLIN_QUERY = "APPEND_TO_CURRENT_GREMLIN_QUERY"
export const RESET_RESULT_ITEMS = "RESET_RESULT_ITEMS"
export const ADD_RESULT_ITEMS = "ADD_RESULT_ITEMS"
export const SET_ALL_AVAILABLE_LABELS = "SET_ALL_AVAILABLE_LABELS"
