import { SET_OUTPUT_TEXT} from '../actions/types.js'


export const initialState = ["[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]", "[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]",]


export default (state = initialState, action) => {
    switch (action.type) {
        case (SET_OUTPUT_TEXT):
            state = action.newText
            return state
        default:
            return state
    }
}