import { GET_OUTPUT_TEXT, SET_OUTPUT_TEXT} from '../actions/types.js'

export default (state = ["[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]", "[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]","[label = 'Person', name = 'Testperson MCTESTNAME', age = 38, city = 'cityNAME', horse = True]",], action) => {
    switch (action.type) {
        case (GET_OUTPUT_TEXT):
            return state
        case (SET_OUTPUT_TEXT):
            state = action.payload
            return state
        default:
            return state
    }
}